### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by GuthrieW** [GuthrieW/GuthrieW#1]
- [x] SHL Cards - Trading
- [x] ISFL Cards - Card Finder
- [x] SHL Bank - Public API
- [x] Jeopardy Bot - Make ready for public use
